//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Drill
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfo
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Removed { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public string CheckDUI { get; set; }
        public Nullable<int> SpeedTickets { get; set; }
        public string CheckCoverage { get; set; }
        public Nullable<decimal> QuoteTotal { get; set; }
    }
}
